const fonts = 
 { "11s0blti":"11S0BLTI.TTF",
"11s0blto":"11S0BLTO.TTF",
"11s0blt":"11S0BLT_.TTF",
"2-954fd":"2-954fd.ttf",
"a brush no":"A Brush No.ttf",
"a bit sketchy":"A bit sketchy.ttf",
"agentred":"AGENTRED.TTF",
"ardourgm":"ARDOURGM.TTF",
"almost japanese comic":"Almost Japanese Comic.ttf",
"ardour3d":"Ardour3d.ttf",
"ardowav":"Ardowav.ttf",
"backto1982":"BACKTO1982.TTF",
"bonk":"Bonk.ttf",
"bonkcoll":"Bonkcoll.ttf",
"bonkfat":"Bonkfat.ttf",
"bonkit":"Bonkit.ttf",
"bonkoff":"Bonkoff.ttf",
"bonkout":"Bonkout.ttf",
"bonkund":"Bonkund.ttf",
"brownwoodnf":"BrownwoodNF.ttf",
"brownwoodshadownf":"BrownwoodShadowNF.ttf",
"burgerdoodlenf":"BurgerDoodleNF.ttf",
"burgerdoodletwonf":"BurgerDoodleTwoNF.ttf",
"comica bd bold":"Comica BD Bold.ttf",
"comica bd":"Comica BD.ttf",
"creature feature":"Creature Feature.ttf",
"diskoteque":"DISKOTEQUE.TTF",
"dancingdonutsnf":"DancingDonutsNF.ttf",
"dayposterblacknf":"DayPosterBlackNF.ttf",
"daypostershadownf":"DayPosterShadowNF.ttf",
"earltik":"Earltik.ttf",
"eastmarketnf":"EastMarketNF.ttf",
"eastmarkettwonf":"EastMarketTwoNF.ttf",
"eyvindur":"Eyvindur.ttf",
"fatfreddiecontour":"FatFreddieContour.ttf",
"fatfreddieshadow":"FatFreddieShadow.ttf",
"grange-shadow":"Grange-Shadow.ttf",
"grange":"Grange.ttf",
"greatlakesnf":"GreatLakesNF.ttf",
"greatlakesshadownf":"GreatLakesShadowNF.ttf",
"hangthedj":"HANGTHEDJ.ttf",
"important":"Important.ttf",
"invited":"Invited.ttf",
"ka-boing!":"Ka-Boing!.ttf",
"letters_":"LETTERS_.TTF",
"lettif__":"LETTIF__.TTF",
"lackawannaweednf":"LackawannaWeedNF.ttf",
"midroba":"Midroba.ttf",
"midrobaschatten":"MidrobaSchatten.ttf",
"nameless harbor":"Nameless Harbor.ttf",
"ode 2 paste up heavy":"Ode 2 Paste Up Heavy.ttf",
"ode 2 paste up plus":"Ode 2 Paste Up Plus.ttf",
"ode 2 paste up":"Ode 2 Paste Up.ttf",
"passage":"Passage.ttf",
"passagegradient":"PassageGradient.ttf",
"quite colorful - ttf":"Quite Colorful - TTF.ttf",
"rabanera-outline-shadow":"Rabanera-outline-shadow.ttf",
"ricksamericannf":"RicksAmericanNF.ttf",
"sf-pro":"SF-Pro.ttf",
"supermassive black hole - ttf":"Supermassive Black Hole - TTF.ttf",
"temploe_":"TEMPLOE_.ttf",
"templof_":"TEMPLOF_.ttf",
"templogo":"TEMPLOGO.ttf",
"templog_":"TEMPLOG_.ttf",
"templok_":"TEMPLOK_.TTF",
"templol_":"TEMPLOL_.ttf",
"templos_":"TEMPLOS_.ttf",
"vtc-komikaheadlinerchewdfat":"VTC-KomikaHeadLinerChewdFat.ttf",
"vtc-komikaheadlinerchewdup":"VTC-KomikaHeadLinerChewdUp.ttf",
"vtc-kreepykomikaone-bold":"VTC-KreepyKomikaOne-Bold.ttf",
"vtc-kreepykomikaone-bolditalic":"VTC-KreepyKomikaOne-BoldItalic.ttf",
"vtc-kreepykomikatwo-bold":"VTC-KreepyKomikaTwo-Bold.ttf",
"vtc-kreepykomikatwo-outline":"VTC-KreepyKomikaTwo-Outline.ttf",
"vtc-kreepykomikatwo-shadow":"VTC-KreepyKomikaTwo-Shadow.ttf",
"vtc-kreepykomikatwo-ultrawide":"VTC-KreepyKomikaTwo-UltraWide.ttf",
"vtcbelialsblade":"VTCBelialsBlade.ttf",
"vtcbelialsblade3d":"VTCBelialsBlade3d.ttf",
"vtcbelialsbladeitalic":"VTCBelialsBladeItalic.ttf",
"vtcbelialsbladeshadow":"VTCBelialsBladeShadow.ttf",
"vtcbelialsbladetricked":"VTCBelialsBladeTricked.ttf",
"vtcswitchbladeromance":"VTCSwitchbladeRomance.ttf",
"vtcswitchbladeromancedrunk":"VTCSwitchbladeRomanceDrunk.ttf",
"vtcswitchbladeromanceitalic":"VTCSwitchbladeRomanceItalic.ttf",
"vtcswitchbladeromanceshadowed":"VTCSwitchbladeRomanceShadowed.ttf",
"vtcswitchbladeromancesloppydrunk":"VTCSwitchbladeRomanceSloppyDrunk.ttf",
"vtcswitchbladeromancetall":"VTCSwitchbladeRomanceTall.ttf",
"vtks dura 3d":"VTKS DURA 3d.ttf",
"vtks good vibrations 2":"VTKS Good Vibrations 2.ttf",
"vtks highlight 2":"VTKS HIGHLIGHT 2.ttf",
"vtks highlight 3":"VTKS HIGHLIGHT 3.ttf",
"vtks highlight":"VTKS HIGHLIGHT.ttf",
"vtkssoluocriativadois":"VTKSSOLUOCRIATIVADOIS.ttf",
"whata-relief-italic":"WhatA-Relief-Italic.ttf",
"whata-relief":"WhatA-Relief.ttf",
"whata-reliefwd":"WhatA-ReliefWd.ttf"
}
module.exports = {fonts};
